### ISSUE TITLE
Question about 2 features which are implemented in .json file.

### ISSUE THREAD

**Issue by rediffusion** [Hyzeta/vscode-theme-github-light#7]
Hello! 🙂

     How these features works?

> "editor.insertSpaces": true,
>  "editor.tabSize": 2

**Comment by yunlingz** [comment]
> Hello! 🙂
> 
> ```
>  How these features works?
> ```
> 
> > "editor.insertSpaces": true,
> > "editor.tabSize": 2

`editor.insertSpaces`: insert spaces when pressing `Tab` (like vim's `expandtab`), `editor.tabSize`: the number of spaces a soft-tab is equal to.

And I think these are vscode's features, not this theme's 🙂🙂🙂

**Comment by rediffusion** [comment]
@chuling 

 Are these features work? I try these:

> "editor.insertSpaces": true,
> "editor.tabSize": 12

...but not working! Try to put in `settings.json` and after here to `Github-Light-Theme-color-theme.json`.

 Can you show me screencast? 🎬🙏

**P.S.** ··· or maybe it's only for terminal not for the editor.

**Comment by yunlingz** [comment]
> @chuling
> 
> Are these features work? I try these:
> 
> > "editor.insertSpaces": true,
> > "editor.tabSize": 12
> 
> ...but not working! Try to put in `settings.json` and after here to `Github-Light-Theme-color-theme.json`.
> 
> Can you show me screencast? 🎬🙏
> 
> **P.S.** ··· or maybe it's only for terminal not for the editor.

For example, if I use your settings:

![image](https://user-images.githubusercontent.com/23468295/75624836-24c08a00-5bf3-11ea-9137-4c9ceb5ed705.png)

Then, if you create a new file named `main-spaces.cc`, vscode will insert 12 spaces as indentation while you hitting tab key (of course, in most cases, indentation are performed automatically by vscode)

![image](https://user-images.githubusercontent.com/23468295/75624870-939de300-5bf3-11ea-880f-6d8e3f8c6645.png)

And, if you open an existing file which was indent by hard-tabs(`\t`), vscode will display one hard-tab with 12 characters.

![image](https://user-images.githubusercontent.com/23468295/75624909-eecfd580-5bf3-11ea-8ee4-a7fd23e0fb2e.png)

And I suggest you to use [editorconfig](https://editorconfig.org/) to maintain consistent coding styles, since different project may have their own style (for example, Linux kernel use 8-char hard-tab, while LLVM coding standard use 2-spaces indentation)
